# docker-openresty .travis.yml
#
# Builds docker-openresty images on Travis CI
#
# https://travis-ci.org/neomantra/docker-openresty
#
#
# Master will build with Docker tag:
#   openresty:<flavor>
#
# Releases should be tagged in git as:
#   <openresty-version>-<docker-version>
#
# This will build with Docker tags:
#   openresty:<openresty-version>-<docker-version>-<flavor>
#   openresty:<openresty-version>-<flavor>
#

sudo: required

services:
  - docker
language: generic
addons:
  apt:
    packages:
    - docker-ce
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest
    --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform
    linux/armhf
  - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - export BUILDKIT_HOST=tcp://0.0.0.0:1234
install: true
jobs:
  include:

    - stage: build docker image for flavors alpine and alpine-fat
      script:
      - export DOCKER_CLI_EXPERIMENTAL=enabled
      - cd ./alpine
      - buildctl build --frontend dockerfile.v0 \
            --debug \
            --local dockerfile=./Dockerfile \
            --local context=./alpine \
            --output type=image,name=jirkachadima/openresty:alpine-armhf \
            --opt platform=linux/armhf \
      - docker image ls
